# Generated by Django 3.2.8 on 2021-10-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockTicker', models.CharField(max_length=4)),
                ('lastUpdated', models.DateTimeField(verbose_name='last updated')),
                ('numTweets', models.IntegerField(default=0)),
                ('positiveSentiment', models.IntegerField(default=0)),
                ('negativeSentiment', models.IntegerField(default=0)),
            ],
        ),
    ]
