# Generated by Django 3.2.8 on 2021-11-08 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField()),
                ('ticker', models.CharField(max_length=255)),
                ('is_retweet', models.BooleanField()),
                ('retweet_count', models.IntegerField()),
                ('fetched_at', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
            ],
        ),
        migrations.AlterField(
            model_name='stockanalysis',
            name='lastUpdated',
            field=models.DateTimeField(verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='stockanalysis',
            name='negativeSentiment',
            field=models.IntegerField(default=0, verbose_name='Negative Sentiment'),
        ),
        migrations.AlterField(
            model_name='stockanalysis',
            name='numTweets',
            field=models.IntegerField(default=0, verbose_name='Number of Tweets'),
        ),
        migrations.AlterField(
            model_name='stockanalysis',
            name='positiveSentiment',
            field=models.IntegerField(default=0, verbose_name='Positive Sentiment'),
        ),
        migrations.AlterField(
            model_name='stockanalysis',
            name='stockTicker',
            field=models.CharField(max_length=5, verbose_name='Stock Ticker'),
        ),
        migrations.CreateModel(
            name='TweetSymbols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='main.tweet')),
            ],
        ),
    ]
