# Generated by Django 3.2.8 on 2021-11-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211108_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
