# Generated by Django 3.2.8 on 2021-11-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211111_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='sentiment',
            field=models.IntegerField(default=-2),
        ),
        migrations.AddField(
            model_name='tweet',
            name='sentiment_version',
            field=models.IntegerField(default=0),
        )
    ]
