# Generated by Django 3.2.8 on 2021-11-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211111_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockanalysis',
            name='numNegativeTweets',
            field=models.IntegerField(default=0, verbose_name='Number of Negative Tweets'),
        ),
        migrations.AlterField(
            model_name='stockanalysis',
            name='numNeutralTweets',
            field=models.IntegerField(default=0, verbose_name='Number of Neutral Tweets'),
        ),
    ]
