# Generated by Django 3.2.8 on 2021-11-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211123_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='topLikedTweet2Id',
            field=models.IntegerField(default=0, verbose_name='The ID of the second most liked tweet'),
        ),
        migrations.AlterField(
            model_name='stockanalysis',
            name='topLikedTweetId',
            field=models.IntegerField(default=0, verbose_name='The ID of the most liked tweet'),
        ),
    ]
