# Generated by Django 3.2.8 on 2021-11-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211123_1320'),
        ('main', '0007_auto_20211123_1328'),
    ]

    operations = [
    ]
