# Generated by Django 3.2.8 on 2021-11-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211123_1603'),
        ('main', '0007_auto_20211123_1328'),
    ]

    operations = [
    ]
