# Generated by Django 3.2.8 on 2021-11-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_0006_auto_20211123_1603_0007_auto_20211123_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
            ],
        ),
    ]
